name: fuzz-short-job

on:
  # manual triggering
  workflow_dispatch:


permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ci-test
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        submodules: recursive

    - name: Build and test
      run: |
        cmake --version
        set -o pipefail
        mkdir build
        cd build
        bash ${{ github.workspace }}/tests/fuzz.sh 10 2>&1 | tee fuzz-log.txt
        cd ..

    - name: Show report
      run: |
        cat build/report.txt
        echo "Fuzzing completed"

    - name: upload-artifact
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: fuzz-log-${{ github.sha }}
        path: "build/fuzz-log.txt"


