name: g++ 7 build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ci-gcc7
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: install simdjson
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        repository: simdjson/simdjson
        path: src/simdjson
    - name: Configure CMake
      run: |
        cmake --version
        rm -rf ${{ github.workspace }}/build && mkdir ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/build ..
    - name: Build
      run: |
        g++ --version
        cd ${{ github.workspace }}/build
        make -j$(nproc)
    - name: Install
      run: |
        cd ${{ github.workspace }}/build
        make install -j$(nproc)
    - name: Diagnostic
      run: date